// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ClipboardController from "./clipboard_controller"
application.register("clipboard", ClipboardController)

import DragController from "./drag_controller"
application.register("drag", DragController)

import KeepScrolledController from "./keep_scrolled_controller"
application.register("keep-scrolled", KeepScrolledController)

import RemovalsController from "./removals_controller"
application.register("removals", RemovalsController)

import ResetOnSubmitController from "./reset_on_submit_controller"
application.register("reset-on-submit", ResetOnSubmitController)
